### ISSUE TITLE
Could not update package db: Please avoid running yay as root/sudo.

### ISSUE THREAD

**Issue by Bouni** [mnussbaum/ansible-yay#2]
Hi,

if I run the task without become:yes it stops without going any furthe, otherwise I get the error "could not update package db: Please avoid running yay as root/sudo."

If I run yay manually I get the same error if I prepend it with sudo, otherwise I get a prompt `[sudo] password for <user>:`

Any idea what I'm doing wrong?

Edit: This is my task:
```
- name: Update system
  #become: yes
  yay:
    update_cache: yes
    upgrade: yes
```
